version: '3.9'

services:
    
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on: 
      - db

  front:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
