export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_MY_CAT_START = 'REGISTER_MY_CAT_START';
export const REGISTER_MY_CAT_SUCCESS = 'REGISTER_MY_CAT_SUCCESS';
export const REGISTER_MY_CAT_FAIL = 'REGISTER_MY_CAT_FAIL';

export const EDIT_MY_CAT_START = 'EDIT_MY_CAT_START';
export const EDIT_MY_CAT_SUCCESS = 'EDIT_MY_CAT_SUCCESS';
export const EDIT_MY_CAT_FAIL = 'EDIT_MY_CAT_FAIL';

export const DELETE_MY_CAT_START = 'DELETE_MY_CAT_START';
export const DELETE_MY_CAT_SUCCESS = 'DELETE_MY_CAT_SUCCESS';
export const DELETE_MY_CAT_FAIL = 'DELETE_MY_CAT_FAIL';