export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GO_TO_LOGIN = 'GO_TO_LOGIN';
export const GO_TO_REGISTER = 'GO_TO_REGISTER';

export const REGISTER_MY_CAT_START = 'REGISTER_MY_CAT_START';
export const REGISTER_MY_CAT_SUCCESS = 'REGISTER_MY_CAT_SUCCESS';
export const REGISTER_MY_CAT_FAIL = 'REGISTER_MY_CAT_FAIL';

export const EDIT_MY_CAT_START = 'EDIT_MY_CAT_START';
export const EDIT_MY_CAT_SUCCESS = 'EDIT_MY_CAT_SUCCESS';
export const EDIT_MY_CAT_FAIL = 'EDIT_MY_CAT_FAIL';

export const DELETE_CAT_START = 'DELETE_CAT_START';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';
export const DELETE_CAT_FAIL = 'DELETE_MY_CAT_FAIL';

export const GET_CAT_START = 'GET_CAT_START';
export const GET_CAT_SUCCESS = 'GET_CAT_SUCCESS';
export const GET_CAT_FAIL = 'GET_CAT_FAIL';

export const SUBMIT_WEIGHT_START = 'SUBMIT_WEIGHT_START';
export const SUBMIT_WEIGHT_SUCCESS = 'SUBMIT_WEIGHT_SUCCESS';
export const SUBMIT_WEIGHT_FAIL = 'SUBMIT_WEIGHT_FAIL';

export const GET_WEIGHTS_START = 'GET_WEIGHTS_START';
export const GET_WEIGHTS_SUCCESS = 'GET_WEIGHTS_SUCCESS';
export const GET_WEIGHTS_FAIL = 'GET_WEIGHTS_FAIL';

export const DELETE_WEIGHTS_START = 'DELETE_WEIGHTS_START';
export const DELETE_WEIGHTS_SUCCESS = 'DELETE_WEIGHTS_SUCCESS';
export const DELETE_WEIGHTS_FAIL = 'DELETE_WEIGHTS_FAIL';